;The line starts with ';' is the comment line to read.

[INPUT]
;Please modify this for local env. Specify the InPreD node. This will appear in the header of the report.
inpred_node = OUS
;Please modify this for local env. Specify the dataset file path of TSOPPI results:
data_path = /data/sample_data/analysis_results/
;Please modify this if you need to specify file encoding as "ISO-8859-1" or other encoding standards in your local environment to read special Norwegian characters.
encoding_sys = utf-8
;Specify the number of filter sections with low priority. (NB: this will also make the script to generate the number of output tables):
filter_col_nu = 4
;Specify the number of max rows of the table per slide starting from the 8th slide in report. This is used to split long tables.
table_max_rows_per_slide = 14
;Please modify this for local env if you use MTF files to import the clinical data into meta file. Specify the version of year of the MTF files.
material_file_version = 2026

[FILTER0-1]
;pecify the column name need to be filtered:
filter_column = CPSR_ACMG_class,CPSR_ClinVar_class
;Specify the key word for the filter column. If there are multiple keywords need to be filtered at the same time, please split them with ','. You can use ' && ' to combine the keywords startswith '!' as one filter condition:
key_word = Likely_Pathogenic,Pathogenic
;Specify the column names need to be transfered to new data file. Split the column names with ','. NB: the column contents must be the same as they are in the sheet.
columns = Gene_symbol,Change_summary,Genomic_location,DNA_change,cDNA_change,Protein_change_short,Coding_status,Depth_tumor_DNA,AF_tumor_DNA,Depth_normal_DNA,AF_normal_DNA,Depth_tumor_RNA,AF_tumor_RNA,TSO500_LocalApp_class,Class_judgement_comments
;Specify the column name to add in the right end of the table to verify this filter condition. NB: if this value is given, a new column will be added into the tables in the report. Same column name in different filter sections will be merged into one filter column.
filter_column_add = Filter_rescued
;Specify the output result file name. Please note that you type should not exceed 31 characters and not contain any of the characters ':' ' \'  '/'  '?'  '*'  '['  or ']':
output_table = pathogenic_germline

[FILTER0-2]
;pecify the column name need to be filtered:
filter_column = Gene_symbol,Protein_change_short
;Specify the key word for the filter column. If there are multiple keywords need to be filtered at the same time, please split them with ','. You can use ' && ' to combine the keywords startswith '!' as one filter condition:
key_word = TERT
;Specify the column names need to be transfered to new data file. Split the column names with ','. NB: the column contents must be the same as they are in the sheet.
columns = Gene_symbol,Change_summary,Genomic_location,DNA_change,cDNA_change,Protein_change_short,Coding_status,Depth_tumor_DNA,AF_tumor_DNA,Depth_normal_DNA,AF_normal_DNA,Depth_tumor_RNA,AF_tumor_RNA,TSO500_LocalApp_class,Class_judgement_comments
;Specify the column name to add in the right end of the table to verify this filter condition. NB: if this value is given, a new column will be added into the tables in the report. Same column name in different filter sections will be merged into one filter column.
filter_column_add = Filter_rescued
;Specify the output result file name. Please note that you type should not exceed 31 characters and not contain any of the characters ':' ' \'  '/'  '?'  '*'  '['  or ']':
output_table = TERT

[FILTER0-3]
;In this filter section, the input data is the combined table generated from FILTER0.
;Specify the column name need to be filtered:
filter_column = Class_judgement
;Specify the key word for the filter column. If there are multiple keywords need to be filtered at the same time, please split them with ','. You can use ' && ' to combine the keywords startswith '!' as one filter condition:
key_word = LikSOM,SOM,LikGL,incon,include
;Specify the column names need to be transfered to new data file. Split the column names with ','. NB: the column contents must be the same as they are in the sheet.
columns = Gene_symbol,Change_summary,Genomic_location,DNA_change,cDNA_change,Protein_change_short,Coding_status,Depth_tumor_DNA,AF_tumor_DNA,Depth_normal_DNA,AF_normal_DNA,Depth_tumor_RNA,AF_tumor_RNA,TSO500_LocalApp_class,Class_judgement_comments
;Specify the miniment number of Depth_tumor for data to choose:
min_depth_tumor_DNA = 0
;Specify the output result file name. Please note that you type should not exceed 31 characters and not contain any of the characters ':' ' \'  '/'  '?'  '*'  '['  or ']':
output_table = preMTBTable_Appendix

[FILTER1]
;In this filter section, the input data is the combined table named 'workingTable' generated from all sections of FILTER0.
;Specify the column name need to be filtered:
filter_column = Coding_status
;Specify the key word for the filter column. If there are multiple keywords need to be filtered at the same time, please split them with ','. You can use ' && ' to combine the keywords startswith '!' as one filter condition. And '!' means NOT:
key_word = !x:noncoding_variant && !synonymous_variant
;Specify the column names need to be transfered to new data file. Split the column names with ','. NB: the column contents must be the same as they are in the sheet.
columns = Gene_symbol,Ensembl_transcript_ID,Exon_number,Protein_change_short,Coding_status,AF_tumor_DNA,Filter_rescued
;Specify the output result file name. Please note that you type should not exceed 31 characters and not contain any of the characters ':' ' \'  '/'  '?'  '*'  '['  or ']':
output_table = sequence_summary

[FILTER2]
;In this filter section, the input data is the combined table named 'workingTable' generated from all sections of FILTER0.
;Specify the column name need to be filtered:
filter_column = Coding_status
;Specify the key word for the filter column. If there are multiple keywords need to be filtered at the same time, please split them with ','. You can use ' && ' to combine the keywords startswith '!' as one filter condition. And '!' means NOT:
key_word = !x:noncoding_variant
;Specify the column names need to be transfered to new data file. Split the column names with ','. NB: the column contents must be the same as they are in the sheet.
columns = Gene_symbol,Genomic_location,DNA_change,cDNA_change,Protein_change_short,Coding_status,Depth_tumor_DNA,AF_tumor_DNA,Filter_rescued
;Specify the output result file name. Please note that you type should not exceed 31 characters and not contain any of the characters ':' ' \'  '/'  '?'  '*'  '['  or ']':
output_table = AllReporVariants_CodingRegion

[FILTER3]
;In this filter section, the input data is the combined table named 'workingTable' generated from all sections of FILTER0.
;Specify the column name need to be filtered:
filter_column = Coding_status
;Specify the key word for the filter column. If there are multiple keywords need to be filtered at the same time, please split them with ','. You can use ' && ' to combine the keywords startswith '!' as one filter condition. And '!' means NOT:
key_word = !x:noncoding_variant && !synonymous_variant
;Specify the column names need to be transfered to new data file. Split the column names with ','. NB: the column contents must be the same as they are in the sheet.
columns = Gene_symbol,Protein_change_short,Coding_status,AF_tumor_DNA
;Specify the output result file name. Please note that you type should not exceed 31 characters and not contain any of the characters ':' ' \'  '/'  '?'  '*'  '['  or ']':
output_table = AllReporVariants_AltProtein

[FILTER4]
;In this filter section, the input data is the combined table named 'workingTable' generated from all sections of FILTER0.
;Specify the column name need to be filtered:
filter_column = Reporting_judgement
;Specify the key word for the filter column. If there are multiple keywords need to be filtered at the same time, please split them with ','. You can use ' && ' to combine the keywords startswith '!' as one filter condition. And '!' means NOT:
key_word = BioMar,VUSpot,AddRes,GLrel
;Specify the column names need to be transfered to new data file. Split the column names with ','. NB: the column contents must be the same as they are in the sheet.
columns = Gene_symbol,Coding_status,Functional_domain,AF_tumor_DNA,CPSR_ACMG_class,Reporting_judgement,Filter_rescued
;Specify the output result file name. Please note that you type should not exceed 31 characters and not contain any of the characters ':' ' \'  '/'  '?'  '*'  '['  or ']':
output_table = Main_Findings 

[TMB]
;Specify the miniment number of AF_tumor:
min_AF_tumor_DNA = 0.05
;Specify the miniment number of Depth_tumor for data to choose:
min_depth_tumor_DNA = 50
;Specify the column name need to be filtered in preMTBTable_Appendix table before TMB canculation:
TMB_filter_column = Coding_status
;Specify the key word for the filter column. If there are multiple keywords need to be filtered at the same time, please split them with ','. You can use ' && ' to combine the keywords startswith '!' as one filter condition. And '!' means NOT:
TMB_filter_key_word = !x:noncoding_variant
TMB_DRUP_filter_key_word = !x:noncoding_variant && !synonymous_variant
